chat_app/models.py
from .extensions import db
from sqlalchemy import ForeignKey
from sqlalchemy.orm import relationship
from datetime import datetime

class Users(db.Model):
    __tablename__ = 'Users'

    id = db.Column(db.Integer, primary_key=True)
    username = db.Column(db.String(25), unique=True, nullable=False)
    password = db.Column(db.String(25), nullable=False)

class Rooms(db.Model):
    __tablename__ = "Rooms"

    id = db.Column(db.Integer, primary_key=True)
    room_name = db.Column(db.String(25), nullable=False)

class RoomMembers(db.Model):
    __tablename__ = "RoomMembers"

    id = db.Column(db.Integer, primary_key=True)
    room_id = db.Column(db.Integer, ForeignKey('Rooms.id'))
    user_id = db.Column(db.Integer, ForeignKey('Users.id'))

    room = relationship('Rooms')
    user = relationship('Users')

class Messages(db.Model):
    __tablename__ = "Messages"

    id = db.Column(db.Integer, primary_key=True)
    room_id = db.Column(db.Integer, ForeignKey('Rooms.id'))
    sender_id = db.Column(db.Integer, ForeignKey('Users.id'))
    content = db.Column(db.String(100), nullable=False)
    timestamp = db.Column(db.DateTime, default=datetime.utcnow)

    room = relationship('Rooms')
    sender = relationship('Users')

class Friends(db.Model):
    __tablename__ = "Friends"

    id = db.Column(db.Integer, primary_key=True)
    user_id = db.Column(db.Integer, ForeignKey('Users.id'))
    friend_id = db.Column(db.Integer, ForeignKey('Users.id'))

    user = relationship('Users', foreign_keys=[friend_id])

chat_app/__init__.py
from flask import Flask
import os
from .events import socketio
from .routes import main
from .extensions import db
from . import models

def create_app():
    app = Flask(__name__)
    app.config["SECRET_KEY"] = 'secret!'
    app.config["DEBUG"] = True

    basedir = os.path.abspath(os.path.dirname(__file__))
    sqlite_path = os.path.join(basedir, "..", "instance", "users.sqlite3")
    
    app.config['SQLALCHEMY_DATABASE_URI'] = os.environ.get("DATABASE_URL") or f"sqlite:///{sqlite_path}"
    app.config['SQLALCHEMY_TRACK_MODIFICATIONS'] = False

    app.register_blueprint(main)
    
    db.init_app(app)
    socketio.init_app(app)

    with app.app_context():
        db.create_all()

    return app

chat_app/routes.py
from flask import Blueprint, render_template, request, session, redirect, url_for, flash
from sqlalchemy.exc import IntegrityError
from .extensions import db
from .models import Users, Friends, Messages, Rooms

main = Blueprint("main", __name__)

def get_private_room(user1, user2):
    return '_'.join(sorted([user1, user2]))

@main.route('/')
def index():
    return render_template('index.html')

@main.route('/signin', methods=["POST", "GET"])
def sign_in():
    if request.method == 'POST':
        action = request.form["action"]

        if action == 'submit':
            user = request.form['username']
            password = request.form['password']
            
            found_user = Users.query.filter_by(username=user).first()
            if found_user and password == found_user.password:
                    session["user"] = user
                    return redirect(url_for('main.friends'))
            else:
                flash('Username and/or Password do not exist')
                return render_template('signin.html')
        else:
            return redirect(url_for('main.index'))
    else:
        if "user" in session:
            return redirect(url_for('main.friends'))
        return render_template('signin.html')

@main.route('/signup', methods=["POST", "GET"])
def sign_up():
    if request.method == 'POST':
        action = request.form["action"]

        if action == 'submit':
            try:
                user = Users(username=request.form['username'], password=request.form['password'])
                db.session.add(user)
                db.session.commit()
                flash("Successfully Signed Up!")
                return redirect(url_for('main.index'))
            except IntegrityError:
                db.session.rollback()
                flash("Username already exists")
                return render_template('signup.html')
        else:
            return redirect(url_for('main.index'))
    else:
        return render_template('signup.html')

@main.route('/friends', methods=['POST', 'GET'])
def friends():
    if request.method == 'POST':
        action = request.form['action']

        if action =='logout':
            return redirect(url_for('main.logout'))
        elif action == 'Enter':
            friend = request.form['friend']
            found_user = Users.query.filter_by(username=friend).first()
            if found_user:
                if found_user.username == session['user']:
                    flash("Cannot add yourself")
                    return redirect(url_for('main.friends'))
                found_user_id = found_user.id
                curr_user_id = Users.query.filter_by(username=session['user']).first().id
                friendship = Friends(user_id=curr_user_id, friend_id=found_user_id)
                db.session.add(friendship)
                db.session.commit()
                return(redirect(url_for('main.friends')))
            flash("User not found")
            return redirect(url_for('main.friends'))
        elif action == 'return':
            return redirect(url_for('main.friends'))
        else:
            return redirect(url_for('main.friends'))
    
    else:
        if "user" in session:
            username = session['user']
            username_id = Users.query.filter_by(username=username).first().id
            friends = Friends.query.filter_by(user_id=username_id).all()
            return render_template('friends.html', user=username, friendlist=friends)
        return redirect(url_for('main.signin'))

@main.route('/chat', methods=['POST', 'GET'])
def chat():
    print("ON CHAT")
    if request.method == "POST":
        return redirect(url_for('main.friends'))
    else:
        if "user" not in session:
            redirect(url_for('main.signin'))
        friend = request.args.get("user")
        found_user = Users.query.filter_by(username=friend).first()
        if found_user:
            room_name = get_private_room(friend, session['user'])
            found_room = Rooms.query.filter_by(room_name=room_name).first()
            if found_room:
                room_id = found_room.id
                past_messages = Messages.query.filter_by(room_id=room_id).order_by(Messages.timestamp.desc()).limit(10).all()
                past_messages.reverse()
                return render_template('chat.html', recipient=friend, curr_user=session["user"], displaymsg=past_messages)
            return render_template('chat.html', recipient=friend, curr_user=session["user"])
        flash("User not found")
        return render_template('chat.html')
        
@main.route('/logout')
def logout():  
    if "user" in session:
        session.pop("user", None)
        return redirect(url_for('main.sign_in'))
    else:
        return redirect(url_for('main.sign_in'))

chat_app/templates/basesign.html
<!DOCTYPE html>
<html>
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <title>SocketIO Chat</title>
    <script src="https://cdn.socket.io/4.5.4/socket.io.min.js"></script>
    <style>
        
        body {
            justify-content: center;
            align-items: center;
        }
        #landing {
            justify-self: center;
            align-items: center;
        }
    </style>
</head>
<body>
    <div id="landing">
        {% block content %}{% endblock %}
    </div>

    {% block scripts %}{% endblock %}
</body>
</html>

chat_app/templates/chat.html
<!DOCTYPE html>
<html>
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <title>Messages</title>
    <script src="https://cdn.socket.io/4.5.4/socket.io.min.js"></script>
    <style>
        #return {
            display:flex;
            justify-content: center;
            align-items: center;
            gap: 30px;
        }
        #messages {
            font-size: 20px;
        }
    </style>
</head>
<body>
    <h1 style="text-align: center;">Message with {{recipient}}</h1>
    <div id="return">
        <form id="msg-form">
            <input type="text" id="msg" name="msg" placeholder = "Enter Message" required>
            <input type="submit" name="action" value="Send">
        </form>
        <form action="{{url_for('main.friends')}}" method="POST">
            <input type="submit" id="return-button" name="action" value="return">
        </form>
    </div>
    <div id="message_box">
        <ul id="messages">
            {% for messages in displaymsg %}
                <li>{{messages.sender.username}} : {{messages.content}}</li>
            {% endfor %}
        </ul>
    </div>
    <script>
        const user1 = "{{curr_user}}";
        const user2 = "{{recipient}}";
    </script>
    <script src="{{ url_for('static', filename='chat.js') }}"></script>
</body>
</html>

chat_app/templates/friends.html
<!DOCTYPE html>
<html>
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <title>kshao's service chat</title>
    <style>
        body {
            justify-content: center;
            align-items: center;
        }
        #landing {
            display:flex;
            justify-content: center;
            align-items: center;
        }
        #searchfriend {
            display:flex;
            justify-content: center;
            align-items: center;
        }
        #error {
            display:flex;
            justify-content: center;
            align-items: center;
        }
        #friendlabel {
            font-size: 40px;
        }
        #friendnames {
            font-size:25px;
        }
    </style>
</head>
<body>
    <h1 style="text-align: center;">{{user}}'s Friends:</h1>
    <div id="searchfriend">
        <form action="#" method="POST">
            <label for="friend">Add Friend:</label>
            <input type="input" name="friend" placeholder="Enter username" required>
            <input type="submit" name="action" value="Enter">
        </form>
    </div>
    <div id="error">
        {% with messages = get_flashed_messages() %}
            {% if messages %}
                {% for msg in messages %}
                    <p><i>{{msg}}</i></p>
                {% endfor %}
            {% endif %}
        {% endwith %}
    </div>
    <br>
        <label id="friendlabel">Friends:</label>
        <ul id="friendnames">
            {% for entry in friendlist %}
                <li><a href="{{ url_for('main.chat') }}?user={{entry.user.username}}">{{ entry.user.username }}</a></li>
            {% endfor %}
        </ul>
    
    <div id="landing">
        <form action="#" method="POST">
            <input type="submit" name="action" value="logout">
        </form>
    </div>
    
</body>
</html>

chat_app/templates/index.html
<!DOCTYPE html>
<html>
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <title>Home Page</title>
    <style>
        #wrapper {
            display: flex;
            justify-content: center;
            align-items: center;
        }
        #flashmessage {
            display: flex;
            justify-content: center;
            align-items: center;
        }
    </style>
</head>
<body>
    <h1 style="text-align: center;">Welcome to kshao's messaging service</h1>

    <div id="wrapper">
        <button id="signin" >Sign-In</button>  
        <button id="signup">Sign-Up</button>
    </div>
    <div id="flashmessage">
        {% with messages = get_flashed_messages() %}
                {% if messages %}
                    {% for msg in messages %}
                        <p><i>{{msg}}</i></p>
                    {% endfor %}
                {% endif %}
        {% endwith %}
    </div>

    <script>
        document.getElementById('signin').onclick = function () {
            window.location.href= "{{ url_for('main.sign_in') }}";
        };

        document.getElementById('signup').onclick = function () {
            window.location.href="{{ url_for('main.sign_up') }}"
        };
    </script>
</body>
</html>

chat_app/templates/signin.html
{% extends "basesign.html" %}

{% block content %}
<h1 style="text-align: center;">Sign In</h1>
<form action="#" method="post">
        <div>
                <label for="username">Username:</label>
                <input type="text" name="username" placeholder="Enter Username" >
        </div>     
        <br>
        <div>
                <label for="password">Password:</label>
                <input type="password" name="password" placeholder="Enter Password" >
        </div> 
        <p><input type="submit" name="action" value="submit"></p>
</form>
        {% with messages = get_flashed_messages() %}
                {% if messages %}
                        {% for msg in messages %}
                                <p><i>{{msg}}</i></p>
                        {% endfor %}
                {% else %}
                        <br>
                {% endif %}
        {% endwith %}
        <form action="#" method="POST">
                <input type="submit" name="action" value="return">
        </form>
{% endblock %}

{% block scripts %}
{% endblock %}

chat_app/templates/signup.html
{% extends "basesign.html" %}

{% block content %}
<h1 style = "text-align: center ;">Sign Up</h1>
<form action="#" method="POST">
        <div>
                <label for="username">Username:</label>
                <input type="text" id="username" name="username" placeholder="Enter Username" required>
        </div>
        {% with messages = get_flashed_messages() %}
                {% if messages %}
                        {% for msg in messages %}
                                <p><i>{{msg}}</i></p>
                        {% endfor %}
                {% else %}
                        <br>
                {% endif %}
        {% endwith %}
        <div>
                <label for="password">Password:</label>
                <input type="password" id="password" name="password" placeholder="Enter Password" required>
        </div>
        <p><input type="submit" name = "action" value="submit"></p>
</form>
        <br>
        <form action="#" method="POST">
                <input type="submit" name = "action" value="return">
        </form>
{% endblock %}

{% block scripts %}
{% endblock %}